# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Horror', 'Horror'), ('Novel', 'Novel'), ('Sci-Fi', 'Sci-Fi')], default='Novel', max_length=200),
        ),
    ]
