# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-29 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20191129_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
