# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20191130_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_img/'),
        ),
    ]
