# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-30 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20191130_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='books',
            name='type',
            field=models.CharField(choices=[('Classic', 'Classic'), ('Horror', 'Horror'), ('Novel', 'Novel'), ('Sci-Fi', 'Sci-Fi')], max_length=200),
        ),
    ]
